config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'homes#show'
	resources :users 
	resources :posts
end

app/models/post.rb
class Post
  include Mongoid::Document
  field :title, type: String
  field :body, type: String
  validates :title ,:body, presence: true
  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  field :avatar , type: String
  field :description , type: String
  mount_uploader :avatar, AvatarUploader
  
  # delegate :username, to: :user, :allow_nil => true       
  field :username       

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def show
		@posts = Post.all
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.new(post_params)
		if @post.save
			redirect_to root_url
		else
			render :new
		end
	end

	private

	def post_params
		params.require(:post).permit(:title,:body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:edit,:update]
	before_action :check_authorization, only: [:edit,:update]
	before_action :set_user
	def show		
	end

	def edit		
	end

	def update		
		if @user.update(user_params)
			redirect_to @user
		else
			flash.now[:alter] = 'show something wrong. please try again'
			render 'edit'	
		end
	end

	private

	def check_authorization
		unless current_user.id == params[:id].to_i
		# redirect_to root_url			
		end
	end

	def set_user
		@user = User.find(params[:id])
	end
	
	def user_params
		params.require(:user).permit(:email,:avatar,:description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def avatar_for(user, options = {size: 80 })
		size = options[:size]
		if user.avatar?
			image_tag user.avatar.url(:thumb), width: size, class: 'avatar_image', style: "border-radius: 50%"
		else
			image_tag 'download.jpg', width: size,class: 'avatar_image', style: "border-radius: 50%"
		end
	end
end

app/views/homes/show.html.erb
<h1>MyApp</h1>
<div class="posts">
	<%= @posts.each do |post| %>
		<h2><%= post.title %></h2>
	<% end %>
</div>	

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Twitter</a>
      <ul class="nav navbar-nav navbar-right">
    	 <li><%= link_to 'tweet', new_post_path, class: "btn btn-info", style: 'border-radius: 24%;  border-image-width: 54% ;font-weight: bold;;height: 46px; top: 9px; border-top-width: 0px;' %></li>        
        <%if user_signed_in?%>
          <li><%= link_to avatar_for(current_user, size: 50), user_path(current_user.id) %></li>
          <li><%= link_to 'sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Signin / Signup', new_user_session_path %></li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  
  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
	<div class="error">
		<h2>
			<%= pluralize(@post.errors.count,'error') %> prohibited this post from begin saved:
		</h2>
		<ul>
			<% @post.errors.full_messages.each do|msg| %>
				<li><%= msg %></li>
			<% end %>	
		</ul>
	</div>
	<% end %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :body %>
	<%= f.text_area :body %>
	<%= f.submit 'Publish' %>
	
<% end %>

app/views/users/edit.html.erb
<h1>Edit profile</h1>
<%= form_for(@user, html: {multipart: true}) do |f| %>
	<%= f.file_field :avatar %><br>
	<%= f.label :description %><br>
	<%= f.text_area :description %><br>
	<%= f.button 'save the change' %>
<% end %>	

app/views/users/show.html.erb
<h1>Profile for <%= @user.email %></h1>
<%= avatar_for(@user) %>
<%= @user.description %>
<%= link_to 'edit', edit_user_path(@user)  %>